services:
  postgres:
    image: postgres:17.4-alpine
    container_name: pizza-api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizza_api
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5440:5432"
    volumes:
      - ./environment/pgdata:/var/lib/postgresql/data/pgdata
